# Generated by Django 3.1.14 on 2022-04-11 11:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_auto_20220331_1914"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="product",
            managers=[
                ("active_products", django.db.models.manager.Manager()),
            ],
        ),
    ]
